<?php

namespace PiedWeb\Crawler;

final class MimeType
{
    /**
     * @var array<string, int>
     */
    public const TYPES = [
        'audio/aac' => 1,
        'application/x-abiword' => 2,
        'application/octet-stream' => 3,
        'video/x-msvideo' => 4,
        'application/vnd.amazon.ebook' => 5,
        'image/bmp' => 6,
        'application/x-bzip' => 7,
        'application/x-bzip2' => 8,
        'application/x-csh' => 9,
        'text/css' => 10,
        'text/csv' => 11,
        'application/msword' => 12,
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document' => 13,
        'application/vnd.ms-fontobject' => 14,
        'application/epub+zip' => 15,
        'image/gif' => 16,
        'text/html' => 17,
        'image/x-icon' => 18,
        'text/calendar' => 19,
        'application/java-archive' => 20,
        'image/jpeg' => 21,
        'application/javascript' => 24,
        'application/json' => 23,
        'audio/midi' => 24,
        'video/mpeg' => 25,
        'application/vnd.apple.installer+xml' => 26,
        'application/vnd.oasis.opendocument.presentation' => 27,
        'application/vnd.oasis.opendocument.spreadsheet' => 28,
        'application/vnd.oasis.opendocument.text' => 29,
        'audio/ogg' => 30,
        'video/ogg' => 31,
        'application/ogg' => 32,
        'font/otf' => 33,
        'image/png' => 34,
        'application/pdf' => 35,
        'application/vnd.ms-powerpoint ' => 36,
        'application/x-rar-compressed' => 37,
        'application/rtf' => 38,
        'application/x-sh' => 39,
        'image/svg+xml' => 40,
        'application/x-shockwave-flash' => 41,
        'application/x-tar' => 42,
        'image/tiff' => 43,
        'application/typescript' => 44,
        'font/ttf' => 45,
        'application/vnd.visio' => 46,
        'audio/x-wav' => 47,
        'audio/webm' => 48,
        'video/webm' => 49,
        'image/webp' => 50,
        'font/woff' => 51,
        'font/woff4' => 52,
        'application/xhtml+xml' => 53,
        'application/vnd.ms-excel ' => 54,
        'application/xml' => 55,
        'application/vnd.mozilla.xul+xml' => 56,
        'application/zip' => 57,
    ];
}
