name: Split Monorepo

on:
    push:
        branches:
            - main
        tags:
            - '*'

env:
    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:

    split_monorepo:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                package:
                    -
                        package: 'crawler'
                    -
                        package: 'curl'
                    -
                        package: 'extractor'
                    -
                        package: 'google'
                    -
                        package: 'google-spreedsheet-seo-scraper'
                    -
                        package: 'text-analyzer'

        steps:
            -   uses: actions/checkout@v3

            # no tag
            -
                if: "!startsWith(github.ref, 'refs/tags/')"
                # Uses an action in the root directory
                name: Monorepo Split of ${{ matrix.package.package }}
                uses: symplify/github-action-monorepo-split@2.1
                env:
                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                with:
                    package_directory: 'packages/${{ matrix.package.package }}'
                    repository_organization: 'piedweb'
                    repository_name: '${{ matrix.package.package }}'
                    user_name: "GitHub Action"
                    user_email: "action@github.com"

            # with tag
            -
                if: "startsWith(github.ref, 'refs/tags/')"
                # Uses an action in the root directory
                name: Monorepo Tagged Split of ${{ matrix.package.package }}
                uses: symplify/github-action-monorepo-split@2.1
                env:
                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                with:
                    tag: ${GITHUB_REF#refs/tags/}
                    package_directory: 'packages/${{ matrix.package.package }}'
                    repository_organization: 'piedweb'
                    repository_name: '${{ matrix.package.package }}'
                    user_name: "GitHub Action"
                    user_email: "action@github.com"